apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "instant-connections.fullname" . }}-app-config
  labels:
    {{- include "instant-connections.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.global.appName | quote }}
  APP_DESCRIPTION: {{ .Values.global.appDescription | quote }}
  ENVIRONMENT: {{ .Values.backend.env.ENVIRONMENT | quote }}
  JITSI_DOMAIN: {{ .Values.backend.env.JITSI_DOMAIN | quote }}
  REDIS_HOST: {{ include "instant-connections.redisHost" . | quote }}
  REDIS_PORT: {{ .Values.externalRedis.port | toString | quote }}
  POSTGRES_SERVER: {{ include "instant-connections.postgresHost" . | quote }}
  POSTGRES_PORT: {{ .Values.externalDatabase.port | toString | quote }}
  POSTGRES_DB: {{ .Values.externalDatabase.database | quote }}
  POSTGRES_USER: {{ .Values.externalDatabase.username | quote }}
