{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "instant-connections.fullname" . }}-worker
  labels:
    {{- include "instant-connections.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "instant-connections.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "instant-connections.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "instant-connections.fullname" . }}-app-config
            - secretRef:
                name: {{ include "instant-connections.fullname" . }}-app-secrets
{{- end }}
