apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instant-connections.fullname" . }}-app-secrets
  labels:
    {{- include "instant-connections.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  POSTGRES_PASSWORD: {{ ternary .Values.postgres.auth.password .Values.externalDatabase.password .Values.postgres.enabled | quote }}
  REDIS_PASSWORD: {{ ternary .Values.redis.auth.password .Values.externalRedis.password .Values.redis.enabled | quote }}
  BOT_INTERNAL_SECRET: {{ .Values.secrets.botInternalSecret | quote }}
  JICOFO_AUTH_PASSWORD: {{ .Values.secrets.jicofoAuthPassword | quote }}
  JVB_AUTH_PASSWORD: {{ .Values.secrets.jvbAuthPassword | quote }}
  OBJECT_STORAGE_ACCESS_KEY: {{ .Values.secrets.objectStorageAccessKey | quote }}
  OBJECT_STORAGE_SECRET_KEY: {{ .Values.secrets.objectStorageSecretKey | quote }}
